-- 1. Ajout de la contrainte d'unicité sur l'URL
ALTER TABLE sources_veille ADD CONSTRAINT sources_veille_url_unique UNIQUE (url);

-- 2. Insertion initiale des 36 sources
INSERT INTO sources_veille (nom, url, score_confiance) VALUES
('GreatYop', 'https://greatyop.com/', 0.8),
('Afri-Carrières', 'https://afri-carrieres.com/', 0.8),
('Mina7 / Mina7Portal', 'https://mina7portal.com/', 0.8),
('Opportunities For Africans (OFA)', 'https://www.opportunitiesforafricans.com/', 0.8),
('World Scholarship Forum', 'https://worldscholarshipforum.com/', 0.7),
('Scholarship Positions', 'https://scholarship-positions.com/', 0.7),
('YouthOP (Youth Opportunities)', 'https://www.youthop.com/scholarships', 0.8),
('Scholars4Dev', 'https://www.scholars4dev.com/', 0.8),
('ScholarshipTab', 'https://www.scholarshiptab.com/', 0.7),
('WeMakeScholars', 'https://www.wemakescholars.com/', 0.7),
('Advance Africa', 'https://www.advance-africa.com/', 0.7),
('Bourse France Excellence Eiffel', 'https://www.campusfrance.org/fr/la-bourse-france-excellence-eiffel', 0.95),
('Campus France', 'https://www.campusfrance.org/', 0.95),
('Chevening Scholarships', 'https://www.chevening.org/', 0.95),
('DAAD - Base de données des bourses', 'https://www2.daad.de/deutschland/stipendium/datenbank/en/', 0.95),
('Fulbright Foreign Student Program', 'https://foreign.fulbrightonline.org/', 0.95),
('MEXT Scholarships (Japon)', 'https://www.studyinjapan.go.jp/en/planning/scholarships/mext-scholarships/', 0.95),
('Türkiye Bursları', 'https://www.turkiyeburslari.gov.tr/', 0.95),
('China Scholarship Council (CSC)', 'https://www.campuschina.org/', 0.95),
('Commonwealth Scholarship Commission (UK)', 'https://cscuk.fcdo.gov.uk/', 0.95),
('Bourses d''excellence de la Confédération suisse (ESKAS)', 'https://www.sbfi.admin.ch/fr/bourses-dexcellence-de-la-confederation-suisse', 0.95),
('Mastercard Foundation Scholars Program', 'https://mastercardfdn.org/all/scholars/', 0.9),
('World Bank Scholarships Program', 'https://www.worldbank.org/en/programs/scholarships', 0.95),
('Banque Africaine de Développement (BAD/AfDB)', 'https://www.afdb.org/', 0.9),
('AUF - Agence Universitaire de la Francophonie', 'https://www.auf.org/nos-actions/bourse/', 0.9),
('UEMOA - Bourses d''Excellence', 'https://www.uemoa.int/bourse-excellence-uemoa', 0.95),
('UNESCO Fellowships', 'https://www.unesco.org/fr/fellowships', 0.9),
('Erasmus Mundus Joint Masters', 'https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters-scholarships', 0.95),
('Togo - Direction des Bourses et Stages (DBS)', 'https://dbs.tg/', 0.95),
('Sénégal - Direction des Bourses', 'https://www.directiondesbourses.sn/', 0.9),
('Côte d''Ivoire - Direction de l''Orientation et des Bourses (DOB)', 'http://www.bourses.enseignement.gouv.ci/', 0.9),
('Côte d''Ivoire - Bourses de Coopération Internationale', 'https://bourses.diplomatie.gouv.ci/', 0.9),
('Bénin - Direction des Bourses et Aides Universitaires (DBAU)', 'https://bourses.enseignementsuperieur.gouv.bj/', 0.9),
('Cameroun - MINESUP', 'https://www.minesup.gov.cm/', 0.9),
('Burkina Faso - CIOSPB', 'https://www.ciospb.gov.bf/', 0.9),
('Mali - DGESRS', 'https://dg-enseignementsup.ml/', 0.9)
ON CONFLICT (url) DO NOTHING;
